"""add notification_logs

Revision ID: 22b6097346c6
Revises: a28184cb3b4d
Create Date: 2026-06-11 10:42:39.785134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b6097346c6'
down_revision: Union[str, None] = 'a28184cb3b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('worker_document_id', sa.Integer(), nullable=False),
    sa.Column('threshold_days', sa.Integer(), nullable=False),
    sa.Column('notification_date', sa.Date(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_document_id'], ['worker_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_document_id', 'threshold_days', 'notification_date', name='uq_notification_once_per_day')
    )
    op.create_index(op.f('ix_notification_logs_id'), 'notification_logs', ['id'], unique=False)
    op.create_index(op.f('ix_notification_logs_notification_date'), 'notification_logs', ['notification_date'], unique=False)
    op.create_index(op.f('ix_notification_logs_project_id'), 'notification_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_worker_document_id'), 'notification_logs', ['worker_document_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_worker_id'), 'notification_logs', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_worker_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_worker_document_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_project_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_notification_date'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    # ### end Alembic commands ###
