"""add_document_categories_fk

Revision ID: 3745d39af0ff
Revises: b3c4d5e6f7a8
Create Date: 2026-06-30 10:42:09.401248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3745d39af0ff'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_document_categories_id'), 'document_categories', ['id'], unique=False)
    op.add_column('document_types', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document_types', 'document_categories', ['category_id'], ['id'])
    op.drop_column('document_types', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_types', sa.Column('category', postgresql.ENUM('MEDICAL', 'BACKGROUND', 'CERTIFICATION', 'TRAINING', 'LEGAL', 'OTHER', name='documentcategory'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_types', type_='foreignkey')
    op.drop_column('document_types', 'category_id')
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='system_settings_pkey')
    )
    op.drop_index(op.f('ix_document_categories_id'), table_name='document_categories')
    op.drop_table('document_categories')
    # system_settings table is not managed by Alembic — intentionally excluded
    # ### end Alembic commands ###
