"""add_is_global_base_requirement_to_document_types

Revision ID: 38ed3b863ecb
Revises: 22b6097346c6
Create Date: 2026-06-11 12:34:25.442878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ed3b863ecb'
down_revision: Union[str, None] = '22b6097346c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('document_types', sa.Column(
        'is_global_base_requirement', sa.Boolean(),
        nullable=False, server_default=sa.false()
    ))
    op.alter_column('document_types', 'is_global_base_requirement', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_types', 'is_global_base_requirement')
    # ### end Alembic commands ###
