"""initial schema

Revision ID: a28184cb3b4d
Revises: 
Create Date: 2026-06-11 10:00:30.139393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28184cb3b4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('MEDICAL', 'BACKGROUND', 'CERTIFICATION', 'TRAINING', 'LEGAL', 'OTHER', name='documentcategory'), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_document_types_id'), 'document_types', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_dni'), 'workers', ['dni'], unique=True)
    op.create_index(op.f('ix_workers_email'), 'workers', ['email'], unique=True)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_table('project_document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'document_type_id', name='uq_project_document_type')
    )
    op.create_index(op.f('ix_project_document_types_document_type_id'), 'project_document_types', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_project_document_types_id'), 'project_document_types', ['id'], unique=False)
    op.create_index(op.f('ix_project_document_types_project_id'), 'project_document_types', ['project_id'], unique=False)
    op.create_table('worker_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADED', 'APPROVED', 'REJECTED', 'EXPIRED', name='documentstatus'), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_documents_document_type_id'), 'worker_documents', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_worker_documents_expiry_date'), 'worker_documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_worker_documents_id'), 'worker_documents', ['id'], unique=False)
    op.create_index(op.f('ix_worker_documents_project_id'), 'worker_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_worker_documents_status'), 'worker_documents', ['status'], unique=False)
    op.create_index(op.f('ix_worker_documents_worker_id'), 'worker_documents', ['worker_id'], unique=False)
    op.create_table('worker_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'project_id', name='uq_worker_project')
    )
    op.create_index(op.f('ix_worker_projects_id'), 'worker_projects', ['id'], unique=False)
    op.create_index(op.f('ix_worker_projects_project_id'), 'worker_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_worker_projects_worker_id'), 'worker_projects', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_projects_worker_id'), table_name='worker_projects')
    op.drop_index(op.f('ix_worker_projects_project_id'), table_name='worker_projects')
    op.drop_index(op.f('ix_worker_projects_id'), table_name='worker_projects')
    op.drop_table('worker_projects')
    op.drop_index(op.f('ix_worker_documents_worker_id'), table_name='worker_documents')
    op.drop_index(op.f('ix_worker_documents_status'), table_name='worker_documents')
    op.drop_index(op.f('ix_worker_documents_project_id'), table_name='worker_documents')
    op.drop_index(op.f('ix_worker_documents_id'), table_name='worker_documents')
    op.drop_index(op.f('ix_worker_documents_expiry_date'), table_name='worker_documents')
    op.drop_index(op.f('ix_worker_documents_document_type_id'), table_name='worker_documents')
    op.drop_table('worker_documents')
    op.drop_index(op.f('ix_project_document_types_project_id'), table_name='project_document_types')
    op.drop_index(op.f('ix_project_document_types_id'), table_name='project_document_types')
    op.drop_index(op.f('ix_project_document_types_document_type_id'), table_name='project_document_types')
    op.drop_table('project_document_types')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_email'), table_name='workers')
    op.drop_index(op.f('ix_workers_dni'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_document_types_id'), table_name='document_types')
    op.drop_table('document_types')
    # ### end Alembic commands ###
