"""add_custom_alert_percentage_to_worker_documents

Revision ID: ef17c1539e20
Revises: 3745d39af0ff
Create Date: 2026-06-30 11:07:47.883522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef17c1539e20'
down_revision: Union[str, None] = '3745d39af0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_documents', sa.Column('custom_alert_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_documents', 'custom_alert_percentage')
    # system_settings table is not managed by Alembic — intentionally excluded
    # ### end Alembic commands ###
